resolver: lts-16.8

compiler: ghc-8.10.2

allow-newer: true

packages:
  - .

extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - th-compat-0.1
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: c06fd0b141054d04614af0ce3015d055a7980bce
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
      - liquid-prelude
      - liquid-containers
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 90e19918bc51a2c246909ec1e4edba636077c675

