resolver: nightly-2020-06-25
packages:
  - .
extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 56d0007e9258a507835ff995acf6c5592262af49
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: a4e303bc55e8f596893e661954e20c983a61215f
